app/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render
from django.urls import include, path
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from perfis.views import CustomLoginView

def custom_404(request, exception):
    return render(request, '404.html', status=404)

def custom_500(request):
    return render(request, '500.html', status=500)

handler404 = custom_404
handler500 = custom_500


urlpatterns = [
    path(
        "", RedirectView.as_view(url="/login", permanent=False), name="index"
    ),
    path('tinymce/', include('tinymce.urls')),
    path("admin/", admin.site.urls),
    path("login/", CustomLoginView.as_view(), name='login'),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path("core/", include("core.urls")),
    path("medicoes/", include("medicoes.urls")),
    path("planos/", include("planos.urls")),
    path("exames/", include("exames.urls")),
    path("perfis/", include("perfis.urls")),
    path('health/', lambda request: HttpResponse('OK'), name='health_check'),
    path("404/",custom_404, name='404' ),
    path("500/",custom_500, name='500' ),
]

if settings.DEBUG:
    # Servindo statics em desenvolvimento
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # Servindo media em desenvolvimento
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("dashboard", views.RelatorioMedicoesView.as_view() , name="dashboard"),
]

exames/urls.py
from django.urls import path
from exames import views
app_name = "exames"
urlpatterns = [
    path('lista/', views.ExameListView.as_view(), name='lista'),
    path('cadastra/', views.CreateExameView.as_view(), name='cadastra'),
    path('<int:pk>/atualiza', views.UpdateExameView.as_view(), name='atualiza'),
    path('<int:pk>/deleta/', views.DeleteExameView.as_view(), name='deleta'),
]

exames/models.py
from django.db import models

from perfis.models import Perfil


class Exame(models.Model):
    data_exame = models.DateField(verbose_name='Data do Exame')
    medico = models.CharField(max_length=100, verbose_name='Médico')
    especialidade = models.CharField(max_length=100, verbose_name='Especialidade do Médico', null=True, blank=True)
    observacoes = models.TextField(null=True, blank=True, verbose_name='Observações')
    exame_arquivo = models.FileField(upload_to='exames', verbose_name='Arquivo',null=True, blank=True)
    perfil = models.ForeignKey(Perfil, verbose_name='Perfil', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.medico} - {self.data_exame.strftime('%d/%m/%Y')}"

    class Meta:
        app_label = 'exames'
        verbose_name = 'Exame'
        verbose_name_plural = 'Exames'
        ordering = ['-data_exame']

exames/forms.py
from django import forms
from exames.models import Exame

class ExameForm(forms.ModelForm):
    data_exame = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'type': 'date',
                'class': 'form-control'
            }
        ),
        label='Data do Exame'
    )

    class Meta:
        model = Exame
        fields = ["data_exame","medico","especialidade","observacoes","exame_arquivo"]
        widgets = {
            'medico': forms.TextInput(attrs={'class': 'form-control'}),
            'especialidade': forms.TextInput(attrs={'class': 'form-control'}),
            'observacoes': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'exame_arquivo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

exames/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView, DeleteView, UpdateView

from exames.forms import ExameForm
from exames.models import Exame
from perfis.models import Perfil


# Create your views here.

class ExameListView(LoginRequiredMixin, ListView):
    model = Exame
    template_name = 'perfil_list.html'

    def get_queryset(self):
        instancia = super().get_queryset().filter(perfil=self.request.user.perfil)
        return instancia


class CreateExameView(LoginRequiredMixin, View):
    model = Exame
    template_name = 'exames/exame_form.html'
    form_class = ExameForm
    success_url = reverse_lazy('exames:lista')

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            perfil = Perfil.objects.get(user=self.request.user)
            form.instance.perfil = perfil
            form.save()
            return redirect(self.success_url)
        else:
            return render(request, self.template_name, {'form': form})

class UpdateExameView(LoginRequiredMixin, UpdateView):
    model = Exame
    form_class = ExameForm
    template_name = 'exames/exame_form.html'
    success_url = "/exames/lista/"

class DeleteExameView(LoginRequiredMixin, DeleteView):
    model = Exame
    template_name = 'exames/exame_confirm_delete.html'
    query_set = Exame.objects.all()
    success_url = '/exames/lista/'

exames/templates/exames/exame_confirm_delete.html
{% extends "base.html" %} {% block content %}
<div class="container-content expandido" id="conteudo">
    <h2 class="m-4 text-center">
    Tem certeza que deseja apagar o exame do {{object.medico }}
    </h2>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Sim, tenho certeza" class="sucesso"/>
        <input class="problema" type="reset" value="Não quero apagar mais"
               onClick="history.back()" />
    </form>
</div>


{% endblock content %}

exames/templates/exames/exame_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 ">
                <input class="btn btn-warning my-3" type="reset" value="Retornar"
                       onClick="history.back()"/>
            </div>
            <div class="col-12">

                <form method="post"  enctype="multipart/form-data" class="form mt-3">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% bootstrap_button button_type="submit" content="OK" %}
                </form>
            </div>
        </div>
    </div>

{% endblock %}

exames/templates/exames/exame_list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container-fluid mt-3">
    <div class="row p-3 bg m-3">
        <div class="col-5">
            <div class="btn-group" role="group" aria-label="Basic example">
                <a class="btn btn-sm btn-warning" href="{% url 'core:dashboard' %}" type="button"><i
                    class="bi bi-arrow-left-circle"></i> Retornar</a>
                <a href="{% url 'exames:cadastra' %}" class="btn btn-primary btn-sm"><i class="bi bi-plus-circle"></i>
                Cadastrar Exame</a>
            </div>
        </div>
    </div>
    <div class="row p-3 bg m-3">
        <div class="col overflow-auto">
            <table class="table table-sm table-striped">
                <thead>
                <tr>
                    <th>Médico</th>
                    <th>Especialidade</th>
                    <th>Observações</th>
                    <th>Data do Exame</th>
                    <th>Arquivo</th>
                    <th>Ações</th>
                </tr>
                </thead>
                <tbody>
                {% for o in object_list %}
                <tr>
                    <td>{{ o.medico }}</td>
                    <td>{{ o.especialidade }}</td>
                    <td>{{ o.observacoes}}</td>
                    <td>{{ o.data_exame }}</td>
                    <td>{% if o.exame_arquivo.url is not None %}
                        <a href="{{ o.exame_arquivo.url }}">Ver exame</a>
                        {% endif %}
                    </td>
                    <td><a href="{% url 'exames:atualiza' pk=o.id %}" class="btn btn-sm btn-primary "><i
                            class="bi bi-pencil-fill"></i></a> |
                        <a href="{% url 'exames:deleta' pk=o.id %}" class="btn btn-sm btn-danger "><i
                                class="bi bi-trash-fill"></i></a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
                <tfoot></tfoot>
            </table>
        </div>
    </div>
</div>
{% endblock %}